import Link from "next/link";
import { notFound } from "next/navigation";
import { requireRole } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { CatalogPreviewActions } from "../../catalog-preview-actions";

export default async function CatalogPreviewPage({ params }: { params: Promise<{ id: string }> }) {
  const currentUser = await requireRole(["SUPER_ADMIN"]); const { id } = await params;
  const catalog = await prisma.catalog.findFirst({ where: { id: Number(id), tenantId: currentUser.tenant!.id }, include: { fields: { where: { enabled: true } }, products: { orderBy: { sortOrder: "asc" }, include: { product: { include: { category: true, variants: { orderBy: { price: "asc" } } } } } } } });
  if (!catalog) notFound();
  const fields = new Set(catalog.fields.map((field) => field.fieldKey)); const printColumns = catalog.layout === "TWO_COLUMNS" ? 2 : catalog.layout === "FOUR_COLUMNS" ? 4 : 3; const columns = catalog.layout === "TWO_COLUMNS" ? "md:grid-cols-2" : catalog.layout === "FOUR_COLUMNS" ? "md:grid-cols-3 xl:grid-cols-4" : "md:grid-cols-2 xl:grid-cols-3";
  return <main className="min-h-screen bg-slate-100 px-4 py-6 sm:px-6"><style>{`@page { size: A4 landscape; margin: 10mm; } @media print { body { background: white !important; } .catalog-screen-controls { display: none !important; } .catalog-grid { grid-template-columns: repeat(${printColumns}, minmax(0, 1fr)) !important; gap: 8px !important; } .catalog-card { break-inside: avoid; box-shadow: none !important; } }`}</style><div className="mx-auto max-w-7xl"><div className="catalog-screen-controls mb-5 flex items-center justify-between print:hidden"><Link href={`/catalogs/${catalog.id}/edit`} className="rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700">Kthehu te editimi</Link><div className="flex items-center gap-3"><span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-semibold text-amber-800">Preview privat</span><CatalogPreviewActions catalogName={catalog.name} publicUrl={catalog.isPublic && catalog.publicSlug ? `/catalog/${catalog.publicSlug}` : null} /></div></div><header className="rounded-[28px] bg-slate-950 px-6 py-10 text-white sm:px-10"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-emerald-300">{currentUser.tenant?.businessName ?? currentUser.tenant?.name}</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">{catalog.name}</h1>{catalog.description ? <p className="mt-3 max-w-2xl text-sm text-white/70">{catalog.description}</p> : null}</header><section className={`catalog-grid mt-6 grid gap-4 ${columns}`}>{catalog.products.map((item) => { const product = item.product; const firstVariant = product.variants[0]; const imagePath = product.variants.find((variant) => variant.imagePath)?.imagePath; const stock = product.variants.reduce((sum, variant) => sum + variant.stock, 0); return <article key={item.id} className="catalog-card rounded-[22px] border border-slate-200 bg-white p-4 shadow-sm">{imagePath ? <img src={imagePath} alt={product.name} className="h-36 w-full rounded-xl bg-slate-100 object-contain p-2" /> : <div className="h-36 rounded-xl bg-slate-100" />}{fields.has("brand") && product.brand ? <p className="mt-4 text-xs font-semibold uppercase tracking-[0.14em] text-emerald-700">{product.brand}</p> : null}{fields.has("name") ? <h2 className="mt-1 font-semibold text-slate-950">{product.name}</h2> : null}{fields.has("category") ? <p className="mt-1 text-sm text-slate-500">{product.category.name}</p> : null}{catalog.priceMode === "RETAIL" ? <p className="mt-3 font-semibold text-slate-950">EUR {Number(firstVariant?.price ?? 0).toFixed(2)}</p> : null}{catalog.stockMode === "EXACT" ? <p className="mt-2 text-sm text-slate-500">Stok: {stock}</p> : null}{catalog.stockMode === "AVAILABILITY" ? <p className={stock ? "mt-2 text-sm font-semibold text-emerald-700" : "mt-2 text-sm font-semibold text-rose-700"}>{stock ? "Ne stok" : "Jasht stokut"}</p> : null}</article>; })}</section></div></main>;
}
