import Image from "next/image";
import Link from "next/link";

const features = [
  ["Inventory Engine", "Real-time multi-location inventory", "Sync inventory across warehouses, stores and sales channels."],
  ["Cloud POS", "Fast checkout, always connected", "Barcode-ready selling with cash, card and register sessions."],
  ["Barcode", "Scan. Find. Update.", "Find variants instantly and keep stock accurate at every movement."],
  ["Purchases", "Supplier to stock", "Purchase orders, receiving, returns and margins in one workflow."],
  ["Orders", "Orders without chaos", "A single workspace for store, phone and online order operations."],
  ["Analytics", "Stock turnover and insight", "Make better purchase decisions with live product and sales data."],
];

function Icon({ name }: { name: string }) {
  return <span className="flex h-9 w-9 items-center justify-center rounded-lg bg-emerald-100 text-sm font-bold text-emerald-800">{name.slice(0, 1)}</span>;
}

function MockWindow({ dark = false, children }: { dark?: boolean; children: React.ReactNode }) {
  return <div className={`overflow-hidden rounded-xl border shadow-[0_18px_52px_rgba(15,23,42,0.16)] ${dark ? "border-slate-700 bg-slate-950" : "border-slate-200 bg-white"}`}><div className={`flex h-9 items-center gap-1.5 px-4 ${dark ? "bg-slate-900" : "bg-slate-50"}`}><i className="h-2.5 w-2.5 rounded-full bg-rose-400" /><i className="h-2.5 w-2.5 rounded-full bg-amber-300" /><i className="h-2.5 w-2.5 rounded-full bg-emerald-400" /><span className={`mx-auto rounded px-16 py-1 text-[9px] ${dark ? "bg-slate-800 text-slate-400" : "bg-white text-slate-400"}`}>app.stockbase.io</span></div>{children}</div>;
}

function DashboardMock() {
  return <MockWindow><div className="bg-[#eff4ff] p-3 sm:p-5"><div className="rounded-lg bg-white p-3 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold text-slate-900">Operations Overview</p><p className="text-[10px] text-emerald-700">Live sync / 4 warehouses</p></div><span className="text-[10px] text-slate-500">Today / EUR</span></div><div className="mt-3 grid grid-cols-2 gap-2 lg:grid-cols-4">{[["Inventory value", " 24,180"],["Active orders", "48"],["Low stock", "14"],["Sales today", " 3,840"]].map(([label,value], index)=><div key={label} className="rounded-md bg-slate-50 p-2"><p className="text-[8px] uppercase tracking-wide text-slate-500">{label}</p><p className={`mt-1 text-sm font-bold ${index===2?"text-rose-600":"text-slate-900"}`}>{value}</p></div>)}</div><div className="mt-3 grid gap-2 lg:grid-cols-3"><div className="rounded-md bg-white p-3 lg:col-span-1"><p className="text-[10px] font-semibold">Weekly velocity</p><div className="mt-4 flex h-20 items-end gap-1">{[35,58,48,72,64,90,76].map((h,i)=><i key={i} style={{height:`${h}%`}} className="flex-1 rounded-t bg-emerald-500" />)}</div></div><div className="rounded-md bg-white p-3 lg:col-span-2"><p className="text-[10px] font-semibold">Recent orders</p>{["#1042 / Ready", "#1041 / Paid", "#1040 / Packed"].map((item)=><div key={item} className="mt-2 flex justify-between border-t pt-1.5 text-[9px] text-slate-600"><span>{item}</span><b className="text-emerald-700">Complete</b></div>)}</div></div></div></div></MockWindow>;
}

export function MarketingHomepage({ supportEmail }: { supportEmail: string }) {
  return <main className="bg-[#f8f9ff] text-[#0b1c30]">
    <header className="sticky top-0 z-50 border-b border-slate-100 bg-white/90 backdrop-blur-xl"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between gap-4 px-5 lg:px-8"><Link href="/" className="flex items-center gap-2.5"><Image src="/stock-app-logo.svg" alt="StockBase" width={31} height={31} /><b className="text-base tracking-tight">StockBase</b></Link><nav className="hidden items-center gap-7 text-sm text-slate-600 lg:flex"><a href="#product">Product</a><a href="#solutions">Solutions</a><a href="#features">Features</a><a href="#pricing">Pricing</a><a href="#resources">Resources</a></nav><div className="flex items-center gap-2"><Link href="/login" className="hidden px-3 py-2 text-sm text-slate-600 sm:block">Log in</Link><Link href="/trial" className="hidden rounded-lg border border-slate-200 px-3 py-2 text-sm font-medium md:block">Book a Demo</Link><Link href="/trial" className="rounded-lg bg-[#006c4a] px-3 py-2 text-sm font-semibold text-white shadow-sm">Start Free Trial</Link></div></div></header>
    <section id="product" className="relative overflow-hidden bg-white"><div className="absolute -left-32 -top-40 h-[520px] w-[520px] rounded-full bg-emerald-100/60 blur-3xl" /><div className="absolute right-0 top-28 h-96 w-96 rounded-full bg-blue-100/60 blur-3xl" /><div className="relative mx-auto max-w-7xl px-5 pb-16 pt-14 text-center lg:px-8 lg:pt-20"><span className="inline-flex items-center gap-2 rounded-full bg-[#eff4ff] px-4 py-2 text-[11px] font-bold uppercase tracking-[0.14em] text-emerald-700"><i className="h-2 w-2 rounded-full bg-emerald-600" /> Multi-location inventory and POS</span><h1 className="mx-auto mt-5 max-w-4xl text-4xl font-bold tracking-[-0.04em] sm:text-5xl lg:text-[54px] lg:leading-[1.12]">Inventory, orders and sales.<br /><span className="text-[#006c4a]">One powerful platform.</span></h1><p className="mx-auto mt-5 max-w-2xl text-base leading-7 text-slate-600">StockBase brings products, inventory, warehouses, purchases, orders and point of sale into one simple platform built for growing businesses.</p><div className="mt-7 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/trial" className="rounded-lg bg-[#006c4a] px-6 py-3 text-sm font-semibold text-white shadow-lg shadow-emerald-900/15">Start Free Trial ?</Link><Link href="/trial" className="rounded-lg bg-white px-6 py-3 text-sm font-semibold shadow-sm ring-1 ring-slate-200">? Book a Demo</Link></div><p className="mt-5 text-xs text-slate-500">? 14-day free trial &nbsp; / &nbsp; ? No credit card required &nbsp; / &nbsp; ? EU hosted</p><div className="relative mx-auto mt-12 max-w-6xl text-left"><div className="absolute -left-5 top-5 hidden rounded-full bg-white px-4 py-2 text-xs shadow-xl lg:block">? Order #1042 completed <b className="text-emerald-700">+ 840</b></div><div className="absolute -right-5 top-28 hidden rounded-full bg-[#131b2e] px-4 py-2 text-xs text-white shadow-xl lg:block">? Stock +120 / Copenhagen</div><DashboardMock /></div></div></section>
    <section id="features" className="bg-[#eff4ff] py-16"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="mx-auto max-w-2xl text-center"><p className="text-xs font-bold uppercase tracking-[0.16em] text-emerald-700">Complete operations</p><h2 className="mt-3 text-3xl font-bold tracking-tight">Everything your business needs to manage stock and sales</h2></div><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{features.map(([eyebrow,title,copy], index)=><article key={title} className={`rounded-xl bg-white p-6 shadow-sm ${index===0||index===3?"md:col-span-2 lg:col-span-2":""}`}><div className="flex items-start justify-between"><Icon name={eyebrow} /><span className="text-xs text-emerald-700">?</span></div><p className="mt-7 text-xs font-bold uppercase tracking-wider text-emerald-700">{eyebrow}</p><h3 className="mt-2 text-xl font-bold">{title}</h3><p className="mt-3 max-w-lg text-sm leading-6 text-slate-600">{copy}</p><div className="mt-6 h-14 rounded-lg bg-[linear-gradient(90deg,#eff4ff,#f8f9ff)]" /></article>)}</div></div></section>
    <section id="solutions" className="bg-white py-16"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="grid gap-10 lg:grid-cols-[0.72fr_1.28fr] lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-emerald-700">Master catalog</p><h2 className="mt-3 text-3xl font-bold tracking-tight">Know exactly what&apos;s in stock</h2><p className="mt-4 leading-7 text-slate-600">A single catalogue for every product, location and sales channel. Keep prices, stock and variants connected.</p><ul className="mt-6 space-y-3 text-sm text-slate-700"><li>? Multi-warehouse availability</li><li>? Safety stock alerts</li><li>? Product variants and barcode labels</li></ul></div><MockWindow><div className="p-4"><div className="flex justify-between"><b className="text-sm">Inventory</b><span className="rounded bg-emerald-50 px-2 text-[10px] text-emerald-700">+ Add product</span></div><div className="mt-4 overflow-hidden rounded-lg border border-slate-200 text-[10px]"><div className="grid grid-cols-5 bg-slate-50 p-2 font-bold text-slate-500"><span>PRODUCT</span><span>SKU</span><span>STOCK</span><span>PRICE</span><span>STATUS</span></div>{["Air Max 270","Wool overshirt","Arc lamp","Canvas tote"].map((name,i)=><div key={name} className="grid grid-cols-5 border-t p-2 text-slate-600"><span className="font-semibold text-slate-800">{name}</span><span>SB-{i+104}</span><span>{14+i*8}</span><span> {90+i*20}</span><span className="text-emerald-700">In stock</span></div>)}</div></div></MockWindow></div></div></section>
    <section className="bg-[#131b2e] py-16 text-white"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.16em] text-emerald-300">Location intelligence</p><h2 className="mt-3 text-3xl font-bold">Your inventory. Across every location.</h2><p className="mt-4 text-slate-300">Move stock between warehouse, store and POS without losing visibility.</p></div><div className="mt-10 grid gap-4 md:grid-cols-3">{["Copenhagen Central","Aarhus Warehouse","Online fulfilment"].map((location,index)=><div key={location} className="rounded-xl border border-white/10 bg-white/5 p-5"><p className="text-xs text-emerald-300">LOCATION 0{index+1}</p><h3 className="mt-2 font-bold">{location}</h3><div className="mt-8 h-12 rounded bg-slate-800" /><p className="mt-3 text-xs text-slate-400">Live inventory sync</p></div>)}</div></div></section>
    <section className="bg-white py-16"><div className="mx-auto grid max-w-6xl gap-10 px-5 lg:grid-cols-2 lg:items-center"><div className="mx-auto w-56 rounded-[28px] bg-[#131b2e] p-3 shadow-2xl"><div className="rounded-[20px] bg-slate-950 p-4 text-white"><p className="text-[10px] text-emerald-300">SCAN PRODUCT</p><div className="mt-8 h-28 rounded-lg border border-dashed border-emerald-400" /><p className="mt-7 text-xs">Barcode / SKU ready</p><div className="mt-3 h-1 rounded bg-emerald-400" /></div></div><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-emerald-700">Barcode workflow</p><h2 className="mt-3 text-3xl font-bold">Scan. Find. Update.</h2><p className="mt-4 leading-7 text-slate-600">Use a phone, laser gun or SKU search to find the exact variant and update stock in seconds.</p><div className="mt-6 grid grid-cols-2 gap-3 text-sm"><div className="rounded-lg bg-[#eff4ff] p-4">Barcode and SKU lookup</div><div className="rounded-lg bg-[#eff4ff] p-4">Instant stock movement</div><div className="rounded-lg bg-[#eff4ff] p-4">POS ready scanner</div><div className="rounded-lg bg-[#eff4ff] p-4">Labels and print</div></div></div></div></section>
    <section className="bg-[#eff4ff] py-16"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.16em] text-emerald-700">Purchases</p><h2 className="mt-3 text-3xl font-bold">From supplier to stock</h2><p className="mt-4 text-slate-600">Create purchase orders, receive partial deliveries and see purchase cost in one controlled flow.</p></div><div className="mt-8 rounded-xl bg-white p-5 shadow-sm"><div className="grid gap-4 md:grid-cols-4">{["Supplier selected","Products in order","Partial receiving","Margin updated"].map((item,i)=><div key={item} className="rounded-lg border border-slate-200 p-4"><span className="text-xs text-emerald-700">0{i+1}</span><p className="mt-2 font-semibold">{item}</p><div className="mt-4 h-2 rounded bg-slate-100" /></div>)}</div></div></div></section>
    <section className="bg-white py-16"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="text-center"><p className="text-xs font-bold uppercase tracking-[0.16em] text-emerald-700">Unified orders</p><h2 className="mt-3 text-3xl font-bold">Orders without the chaos</h2></div><div className="mt-8 rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap gap-2 text-xs"><span className="rounded-full bg-slate-100 px-3 py-1">All orders</span><span className="rounded-full bg-emerald-100 px-3 py-1 text-emerald-800">Store POS</span><span className="rounded-full bg-slate-100 px-3 py-1">Phone orders</span></div><div className="mt-5 grid grid-cols-4 border-b pb-3 text-[10px] font-bold text-slate-500"><span>ORDER</span><span>CUSTOMER</span><span>CHANNEL</span><span>STATUS</span></div>{["#1024 / Emma","#1023 / Sara","#1022 / Nordic Store"].map((order)=><div key={order} className="grid grid-cols-4 border-b py-3 text-xs"><span className="font-semibold">{order}</span><span>Customer</span><span>Store POS</span><span className="text-emerald-700">Ready to pack</span></div>)}</div></div></section>
    <section className="bg-[#131b2e] py-16 text-white"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.16em] text-emerald-300">Cloud POS</p><h2 className="mt-3 text-3xl font-bold">From stockroom to checkout</h2><p className="mt-4 text-slate-300">A focused touch POS for modern retail teams.</p></div><div className="mt-8 grid gap-4 rounded-xl border border-white/10 bg-slate-950 p-4 lg:grid-cols-[1.5fr_0.8fr]"><div className="grid grid-cols-3 gap-3">{["nike.jpg","IMG_6366.webp","bg1.jpg","nike.jpg","IMG_6366.webp","bg1.jpg"].map((image,index)=><div key={index} className="overflow-hidden rounded-lg bg-slate-800"><Image src={`/${image}`} alt="Product" width={220} height={150} className="h-28 w-full object-cover" /><p className="p-2 text-xs">Product {index+1}</p></div>)}</div><div className="rounded-lg bg-slate-900 p-4"><p className="text-xs text-emerald-300">CURRENT SALE</p><h3 className="mt-2 font-bold">Cart</h3><div className="mt-5 space-y-3 text-sm text-slate-300"><p>Nike Air Max <b className="float-right text-white">120</b></p><p>Canvas tote <b className="float-right text-white">60</b></p></div><p className="mt-10 text-2xl font-bold">180.00</p><button className="mt-4 w-full rounded-lg bg-emerald-500 py-3 text-sm font-bold text-slate-950">Complete sale</button></div></div></div></section>
    <section className="bg-white py-16"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="grid gap-8 lg:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-emerald-700">Sales catalogue</p><h2 className="mt-3 text-3xl font-bold">Turn inventory into a sales catalog</h2><p className="mt-4 text-slate-600">Select products, control prices and share a professional catalogue with wholesale customers.</p></div><div className="grid grid-cols-3 gap-3">{["nike.jpg","IMG_6366.webp","bg1.jpg"].map((image,index)=><div key={image} className="rounded-lg border border-slate-200 p-2"><Image src={`/${image}`} alt="Catalog item" width={160} height={110} className="h-20 w-full rounded object-cover" /><p className="mt-2 text-xs font-bold">Catalog item</p><p className="text-[10px] text-emerald-700"> {90+index*20}</p></div>)}</div></div></div></section>
    <section className="bg-[#eff4ff] py-16"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="text-center"><p className="text-xs font-bold uppercase tracking-[0.16em] text-emerald-700">Connected workflow</p><h2 className="mt-3 text-3xl font-bold">One connected workflow</h2></div><div className="mt-8 grid gap-3 md:grid-cols-4">{["Purchase order","Warehouse intake","Orders and POS","Analytics"].map((item,index)=><div key={item} className="rounded-xl bg-white p-5 text-center shadow-sm"><span className="text-emerald-700">0{index+1}</span><p className="mt-3 font-semibold">{item}</p></div>)}</div></div></section>
    <section className="bg-white py-16"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="grid gap-8 lg:grid-cols-[0.7fr_1.3fr]"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-emerald-700">Business intelligence</p><h2 className="mt-3 text-3xl font-bold">See what&apos;s happening in your business</h2><p className="mt-4 text-slate-600">Actionable inventory turnover, product margins and stockout data.</p></div><div className="grid gap-3 sm:grid-cols-3">{[["4.2x","Inventory turnover"],["24,180 DKK","Stock value"],["14 Days","Runout alert"]].map(([value,label])=><div key={label} className="rounded-xl bg-[#eff4ff] p-5"><p className="text-2xl font-bold">{value}</p><p className="mt-2 text-xs text-slate-600">{label}</p></div>)}</div></div></div></section>
    <section id="pricing" className="bg-[#eff4ff] py-16"><div className="mx-auto max-w-7xl px-5 text-center lg:px-8"><p className="text-xs font-bold uppercase tracking-[0.16em] text-emerald-700">Built for every workflow</p><h2 className="mt-3 text-3xl font-bold">Work wherever your business happens</h2><div className="mt-8 grid gap-4 md:grid-cols-3">{[["Desktop and web app","Full operations workspace"],["Tablet POS register","Fast counter checkout"],["Handheld scanner","Mobile stock work"]].map(([title,copy])=><article key={title} className="rounded-xl bg-white p-6 shadow-sm"><div className="mx-auto h-10 w-10 rounded-lg bg-emerald-100" /><h3 className="mt-4 font-bold">{title}</h3><p className="mt-2 text-sm text-slate-600">{copy}</p></article>)}</div></div></section>
    <section className="bg-white py-16"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="text-center"><p className="text-xs font-bold uppercase tracking-[0.16em] text-emerald-700">Trusted by operators</p><h2 className="mt-3 text-3xl font-bold">Trusted by European retail innovators</h2></div><div className="mt-8 grid gap-4 md:grid-cols-3">{["StockBase eliminated our warehouse blind spots across four locations.","The POS and live transfer tracking work without hiccups.","Moving from legacy ERP was seamless for our supplier POs."].map((quote,index)=><blockquote key={quote} className="rounded-xl border border-slate-200 p-6 text-sm leading-7 text-slate-600">{quote}<footer className="mt-5 text-xs font-bold text-slate-900">Retail operator / Europe {index+1}</footer></blockquote>)}</div></div></section>
    <section className="bg-[#131b2e] py-20 text-center text-white"><div className="mx-auto max-w-2xl px-5"><p className="text-xs font-bold uppercase tracking-[0.16em] text-emerald-300">Start today</p><h2 className="mt-3 text-3xl font-bold">Ready to take control of your inventory?</h2><p className="mt-4 text-slate-300">Bring stock, sales and operations into one platform.</p><div className="mt-7 flex justify-center gap-3"><Link href="/trial" className="rounded-lg bg-emerald-500 px-5 py-3 text-sm font-bold text-slate-950">Start free trial</Link><a href={`mailto:${supportEmail}`} className="rounded-lg border border-white/20 px-5 py-3 text-sm font-semibold">Contact sales</a></div></div></section>
    <footer id="resources" className="bg-white py-12"><div className="mx-auto grid max-w-7xl gap-10 px-5 md:grid-cols-6 lg:px-8"><div className="md:col-span-2"><div className="flex items-center gap-2"><Image src="/stock-app-logo.svg" alt="StockBase" width={28} height={28} /><b>StockBase</b></div><p className="mt-4 max-w-sm text-sm leading-6 text-slate-600">Inventory intelligence and operational tools for European retail teams.</p><p className="mt-5 text-xs text-emerald-700">? Systems operational</p></div>{[["Product","Inventory / Orders / POS / Catalog"],["Company","About / Contact"],["Resources","Help / Documentation"],["Legal","Privacy / Terms"]].map(([title,links])=><div key={title}><p className="text-xs font-bold uppercase tracking-wider">{title}</p><p className="mt-4 whitespace-pre-line text-sm leading-7 text-slate-600">{links.replaceAll(" / ","\n")}</p></div>)}</div><div className="mx-auto mt-10 flex max-w-7xl flex-col gap-3 border-t border-slate-100 px-5 pt-6 text-xs text-slate-500 sm:flex-row sm:justify-between lg:px-8"><span> 2026 StockBase. Built in Europe.</span><span>Privacy Statement / Terms of Service / Security Standards</span></div></footer>
  </main>;
}
