"use client";

import { useMemo, useRef, useState } from "react";

export type CatalogProductOption = { id: number; name: string; brand: string | null; category: string; variants: number; price: number; imagePath: string | null; warehouseIds?: number[] };
type Field = { key: string; label: string; enabled: boolean; sortOrder: number };
type InitialCatalog = { id?: number; name: string; description: string; status: string; layout: string; style: string; isPublic: boolean; publicSlug: string; priceMode: string; stockMode: string; productIds: number[]; fields: Field[] };

const DEFAULT_FIELDS: Field[] = [
  ["image", "Foto"], ["name", "Emri"], ["brand", "Brandi"], ["category", "Kategoria"], ["retailPrice", "Cmimi i shitjes"], ["wholesalePrice", "Cmimi wholesale"], ["color", "Ngjyra"], ["size", "Madhesia"], ["material", "Materiali"], ["sku", "SKU"], ["barcode", "Barcode"], ["stock", "Stoku"], ["description", "Pershkrimi"],
].map(([key, label], sortOrder) => ({ key, label, sortOrder, enabled: ["image", "name", "brand", "retailPrice"].includes(key) }));

export function CatalogBuilder({ products, warehouses = [], initialCatalog, action }: { products: CatalogProductOption[]; warehouses?: { id: number; name: string }[]; initialCatalog?: InitialCatalog; action: (formData: FormData) => void | Promise<void> }) {
  const formRef = useRef<HTMLFormElement>(null);
  const initial = initialCatalog ?? { name: "", description: "", status: "DRAFT", layout: "THREE_COLUMNS", style: "MINIMAL", isPublic: false, publicSlug: "", priceMode: "RETAIL", stockMode: "HIDE", productIds: [], fields: DEFAULT_FIELDS };
  const [selectedIds, setSelectedIds] = useState<number[]>(initial.productIds);
  const [fields, setFields] = useState<Field[]>(initial.fields.length ? DEFAULT_FIELDS.map((field) => ({ ...field, ...initial.fields.find((item) => item.key === field.key) })) : DEFAULT_FIELDS);
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("");
  const [brand, setBrand] = useState("");
  const [warehouseId, setWarehouseId] = useState("");
  const [step, setStep] = useState(1);
  const categories = useMemo(() => [...new Set(products.map((product) => product.category))].sort(), [products]);
  const brands = useMemo(() => [...new Set(products.map((product) => product.brand).filter(Boolean) as string[])].sort(), [products]);
  const filtered = useMemo(() => products.filter((product) => (!query || `${product.name} ${product.brand ?? ""}`.toLowerCase().includes(query.toLowerCase())) && (!category || product.category === category) && (!brand || product.brand === brand) && (!warehouseId || product.warehouseIds?.includes(Number(warehouseId)))), [products, query, category, brand, warehouseId]);
  const toggle = (id: number) => setSelectedIds((current) => current.includes(id) ? current.filter((value) => value !== id) : [...current, id]);
  const selectFiltered = () => setSelectedIds((current) => [...new Set([...current, ...filtered.map((product) => product.id)])]);

  return (
    <form ref={formRef} onSubmit={(event) => event.preventDefault()} className="mx-auto max-w-7xl space-y-5 pb-10">
      {initial.id ? <input type="hidden" name="id" value={initial.id} /> : null}
      <input type="hidden" name="productIds" value={JSON.stringify(selectedIds)} />
      <input type="hidden" name="fields" value={JSON.stringify(fields)} />
      <section className="mx-auto flex max-w-3xl flex-col gap-4 rounded-[26px] border border-slate-200 bg-white p-5 shadow-sm lg:flex-row lg:items-center lg:justify-between">
        <div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-emerald-700">Catalog Builder</p><h1 className="mt-1 text-2xl font-semibold tracking-tight text-slate-950">{initial.id ? "Edito katalogun" : "Krijo katalog"}</h1></div>
        <div className="flex items-center gap-2"><span className="mr-2 text-sm font-semibold text-slate-500">Hapi {step}/3</span>{step > 1 ? <button type="button" onClick={() => setStep(step - 1)} className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold text-slate-700">Mbrapa</button> : null}{step < 3 ? <button type="button" onClick={() => setStep(step + 1)} className="rounded-xl bg-slate-950 px-5 py-2.5 text-sm font-semibold text-white">Vazhdo</button> : <button type="button" onClick={() => { if (formRef.current) void action(new FormData(formRef.current)); }} className="rounded-xl bg-emerald-600 px-5 py-2.5 text-sm font-semibold text-white">Gjenero katalogun</button>}</div>
      </section>

      <section className="mx-auto max-w-3xl space-y-5">
        <div className="space-y-5">
          <div className={step === 1 ? "rounded-[24px] border border-slate-200 bg-white p-5" : "hidden"}><h2 className="font-semibold text-slate-950">1. Informacioni baze</h2><div className="mt-4 grid gap-3"><input required name="name" defaultValue={initial.name} placeholder="Emri i katalogut" className="rounded-xl border border-slate-200 px-3 py-2.5 outline-none focus:border-emerald-500" /><textarea name="description" defaultValue={initial.description} placeholder="Pershkrimi (opsional)" className="min-h-20 rounded-xl border border-slate-200 px-3 py-2.5 outline-none focus:border-emerald-500" /><div className="grid grid-cols-2 gap-3"><select name="status" defaultValue={initial.status} className="rounded-xl border border-slate-200 px-3 py-2.5"><option value="DRAFT">Draft</option><option value="ACTIVE">Aktiv</option></select><input name="publicSlug" defaultValue={initial.publicSlug} placeholder="public slug" className="rounded-xl border border-slate-200 px-3 py-2.5" /></div><label className="flex items-center gap-2 text-sm font-medium text-slate-700"><input name="isPublic" type="checkbox" defaultChecked={initial.isPublic} className="h-4 w-4 accent-emerald-600" /> Katalog publik</label></div></div>
          <div className={step === 3 ? "space-y-5" : "hidden"}><div className="rounded-[24px] border border-slate-200 bg-white p-5"><h2 className="font-semibold text-slate-950">3. Pamja dhe cmimet</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><select name="layout" defaultValue={initial.layout} className="rounded-xl border border-slate-200 px-3 py-2.5"><option value="TWO_COLUMNS">2 karta</option><option value="THREE_COLUMNS">3 karta</option><option value="FOUR_COLUMNS">4 karta</option></select><select name="style" defaultValue={initial.style} className="rounded-xl border border-slate-200 px-3 py-2.5"><option value="MINIMAL">Minimal</option><option value="PREMIUM">Premium</option><option value="WHOLESALE">Wholesale</option></select><select name="priceMode" defaultValue={initial.priceMode} className="rounded-xl border border-slate-200 px-3 py-2.5"><option value="RETAIL">Cmimi i shitjes</option><option value="WHOLESALE">Cmim wholesale</option><option value="HIDE">Fshih cmimet</option></select><select name="stockMode" defaultValue={initial.stockMode} className="rounded-xl border border-slate-200 px-3 py-2.5"><option value="HIDE">Fshih stokun</option><option value="EXACT">Shfaq stokun</option><option value="AVAILABILITY">Vetem disponueshmeria</option></select></div></div><div className="rounded-[24px] border border-slate-200 bg-white p-5"><h2 className="font-semibold text-slate-950">Fushat qe shfaqen</h2><div className="mt-4 grid grid-cols-2 gap-2">{fields.map((field) => <label key={field.key} className="flex items-center gap-2 rounded-lg bg-slate-50 px-3 py-2 text-sm text-slate-700"><input type="checkbox" checked={field.enabled} onChange={() => setFields((current) => current.map((item) => item.key === field.key ? { ...item, enabled: !item.enabled } : item))} className="accent-emerald-600" /> {field.label}</label>)}</div></div></div>
        </div>
        <div className={step === 2 ? "rounded-[24px] border border-slate-200 bg-white p-5" : "hidden"}><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold text-slate-950">2. Zgjidh produktet</h2><p className="mt-1 text-sm text-slate-500">{selectedIds.length} produkte te zgjedhura</p></div><button type="button" onClick={selectFiltered} className="rounded-lg border border-emerald-200 bg-emerald-50 px-3 py-2 text-sm font-semibold text-emerald-700">Zgjidh te gjitha te filtruarat ({filtered.length})</button></div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Kerko produkt" className="rounded-xl border border-slate-200 px-3 py-2.5" /><select value={category} onChange={(event) => setCategory(event.target.value)} className="rounded-xl border border-slate-200 px-3 py-2.5"><option value="">Kategorite</option>{categories.map((value) => <option key={value}>{value}</option>)}</select><select value={brand} onChange={(event) => setBrand(event.target.value)} className="rounded-xl border border-slate-200 px-3 py-2.5"><option value="">Brandet</option>{brands.map((value) => <option key={value}>{value}</option>)}</select><select value={warehouseId} onChange={(event) => setWarehouseId(event.target.value)} className="rounded-xl border border-slate-200 px-3 py-2.5"><option value="">Te gjitha depot</option>{warehouses.map((warehouse) => <option key={warehouse.id} value={warehouse.id}>{warehouse.name}</option>)}</select></div><div className="mt-4 max-h-[440px] space-y-2 overflow-y-auto pr-1">{filtered.map((product) => <label key={product.id} className="flex cursor-pointer items-center gap-3 rounded-xl border border-slate-200 p-3 transition hover:border-emerald-200 hover:bg-emerald-50/30"><input type="checkbox" checked={selectedIds.includes(product.id)} onChange={() => toggle(product.id)} className="h-4 w-4 accent-emerald-600" />{product.imagePath ? <img src={product.imagePath} alt="" className="h-12 w-12 rounded-lg border border-slate-200 object-cover" /> : <div className="h-12 w-12 rounded-lg bg-slate-100" />}<div className="min-w-0 flex-1"><p className="truncate font-semibold text-slate-900">{product.brand ? `${product.brand} ${product.name}` : product.name}</p><p className="mt-0.5 text-xs text-slate-500">{product.category} / {product.variants} variante / EUR {product.price.toFixed(2)}</p></div></label>)}</div></div>
      </section>
    </form>
  );
}
