ALTER TABLE "PurchaseOrderItem"
ADD COLUMN "returnedQuantity" INTEGER NOT NULL DEFAULT 0;

ALTER TYPE "PurchaseOrderStatus" ADD VALUE IF NOT EXISTS 'PARTIALLY_RETURNED';
ALTER TYPE "PurchaseOrderStatus" ADD VALUE IF NOT EXISTS 'RETURNED';

ALTER TYPE "StockMovementReason" ADD VALUE IF NOT EXISTS 'SUPPLIER_RETURN';
